name: Bug Report
description: Помогите нам сделать библиотеку vk-miniapps-deploy более стабильной
title: '[Bug]: '
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Описание
      description: Расскажите о вашей проблеме.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Версия vk-miniapps-deploy
      description: Поможет локализовать проблему.
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Платформа
      description: Выберите одну или несколько платформ, на которых воспроизводится ошибка.
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Шаги воспроизведения
      description: Желательно описать последовательность, при которой ошибка стабильно воспроизводится.
    validations:
      required: true
  - type: textarea
    id: expectations
    attributes:
      label: Ожидаемое поведение
      description: Если считаете, что из описания ожидаемое поведение непонятно.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Скриншоты
      description: Прикрепите скриншоты, если есть такая возможность.
  - type: textarea
    id: reproduce-example
    attributes:
      label: Код, который вызвал ошибку
      description: Вы можете привести листинг кода.
  - type: markdown
    attributes:
      value: |
        Спасибо за то, что помогаете нам стать лучше!